Fix denisarger 126
glokascom/bibleVis pull request #149
Opened 2024-09-17 09:01 UTC by DenisArger

#139 - fixed updating the list of possible tags after adding a new image with new tags
#130 - fixed the mechanism for updating the page after deleting the image, fixed the mechanism for setting likes/dislikes
#128 - Fixed the security warning
#145 - fixed the mechanism for changing the user name (added rules)
##147 - added alphabetical sorting of sofware and tag
#144 - added the display of the user's avatar on the gratitude page
#146 - added comma handling when adding tags

2024-09-18 13:47 UTC, Valyukhov commented
при смене username у меня прошел такой

![изображение](https://github.com/user-attachments/assets/4976db1a-34fe-4900-b09b-ec53d438c1f6)
Не выполнен пункт из User story

**4. Character Placement Rules**
No consecutive underscores or hyphens (e.g., __, --, _-, -_ are not allowed).
Cannot end with an underscore _ or hyphen -. (example bob_ and bob- not allowed)  
Cannot contain spaces or other whitespace characters.
Rationale: Prevents formatting issues and potential user impersonation through visually similar usernames.

2024-09-18 14:20 UTC, Valyukhov commented on app/(web)/user/upload/actions/getSoftwares.js
> +    console.log(27)
а почему console.log(27)?

2024-09-18 14:29 UTC, Valyukhov commented on app/api/upload-image/route.ts
> +    revalidatePath('/', 'layout')
может делать ревалидацию не всего сайта?
если тебе нужно обновить теги, ты их используешь на странице upload-image? вот её и валидировать
revalidatePath('/upload-image') 
ну и проверить ещё страницу редактирования картинки

2024-09-18 14:35 UTC, Valyukhov commented on app/components/TagInput.jsx
> +      updateSuggestions(value, selectedTags)
Сложно написано, может так?
```
  if (value.endsWith(',')) {
    const trimmedValue = value.slice(0, -1).trim()
    if (trimmedValue) addTagsFromInput(trimmedValue)
    setInputValue('')
    return
  }
  if (isTagInput || value.length <= limitLettersAllTags) {
    setInputValue(value)
  }
  updateSuggestions(value, selectedTags)
```

2024-09-19 05:32 UTC, Valyukhov commented on app/api/auth/signup/route.ts
> +  validateContent,
https://github.com/glokascom/bibleVis/issues/91
можно ли сказать что эта задача решена @foxprogs ?

2024-09-19 07:51 UTC, Valyukhov commented on app/(web)/[@username]/components/Gallery.js
> +                  userId={userId}
здесь передаём `userId,` а в компоненте `ImageForGallery` этого параметра нет

2024-09-19 10:06 UTC, foxprogs requested changes
есть комментарии

2024-09-19 10:06 UTC, foxprogs commented on app/(web)/user/upload/actions/getSoftwares.js
>  export async function getDataFromTable(tableName) {
а что это за функция такая? Получается я могу из любой таблицы получить все поля? Это плохая практика. Надо добавить просто рлс на нее и без сервисного ключа работать. Потому что список софта - это не что-то сенситив

2024-09-19 10:06 UTC, foxprogs commented on app/(web)/user/upload/actions/getSoftwares.js
> +export async function updateLayot() {
Layout

2024-09-19 10:06 UTC, foxprogs commented on app/api/auth/signup/route.ts
> +  validateContent,
наверное да

2024-09-19 12:02 UTC, DenisArger commented on app/(web)/[@username]/actions/imagesActions.ts
> +  if (!currentUser || !currentUser.user) {
ок, заберу тогда твои изменения

2024-09-19 12:02 UTC, DenisArger commented on app/(web)/[@username]/components/Gallery.js
> +  useEffect(() => {
ок, тоже заберу тогда твои изменения

2024-09-19 13:45 UTC, foxprogs approved these changes

2024-09-19 17:01 UTC, Valyukhov approved these changes

2024-09-19 17:57 UTC, merged