Bugs denisarger 215
glokascom/bibleVis pull request #219
Opened 2024-10-01 08:20 UTC by DenisArger

#213 - upload cover

2024-10-01 09:15 UTC, foxprogs requested changes
не верно отрабатывает инкремент

2024-10-01 15:22 UTC, Pavel064 approved these changes
у меня нет вопросов, нужно только закрыть комментарии от Виктора

2024-10-07 14:07 UTC, Pavel064 reviewed
поправить положение футера на странице поиска

2024-10-09 09:47 UTC, DenisArger commented
> поправить положение футера на странице поиска

это подправил в ишью по поиску

2024-10-09 12:51 UTC, Valyukhov commented on app/(web)/s/[query]/actions/getImageCounts.js
> +      .textSearch('fts', formattedQuery)
3 запроса сразу,
а  если нам нужно только кол-во,
может  `humanMade = totalImages.length-aiImages.length?`

2024-10-09 15:06 UTC, Pavel064 approved these changes

2024-10-09 19:33 UTC, merged