Feat database and auth denisarger 6
glokascom/bibleVis pull request #25
Opened 2024-08-08 08:59 UTC by DenisArger

connect SB and add SignIn anf Login

2024-08-08 12:02 UTC, foxprogs commented on .vscode/extensions.json
> +  "recommendations": ["denoland.vscode-deno"]
а это точно надо?

2024-08-08 12:02 UTC, foxprogs commented on .vscode/settings.json
> +  "deno.unstable": true,
и вот тут?

2024-08-08 12:03 UTC, foxprogs commented on app/[lng]/check-email/page.js
> +'use client'
почему он клиентский?

2024-08-08 12:05 UTC, foxprogs commented on app/[lng]/error/page.jsx
> +'use client'
тут тоже можно сделать серверный компонент. Но я так понимаю это просто временный файл, потом его удалят? Поставь может тудушку, чтоб мы не забыли его убрать потом

2024-08-08 12:07 UTC, foxprogs commented on app/[lng]/password-reset-sent/page.js
> +'use client'
тут тоже можно не клиентский сделать а серверный и там вместо button добавить ссылку

2024-08-08 12:10 UTC, foxprogs commented on app/api/auth/logout/route.js
> +  return NextResponse.json({ message: 'Выход выполнен успешно' })
Если этот код остается, то я бы заменил русский текст на англ

2024-08-08 12:11 UTC, foxprogs commented on app/supabase/middleware.js
> +        },
это уже депрекейтед, надо заменить

2024-08-08 12:14 UTC, foxprogs commented on supabase/config.toml
> +enable_signup = true
false

2024-08-08 12:15 UTC, foxprogs commented on supabase/config.toml
> +enabled = false
google
true

И у тебя почему-то не настроено чтобы с локальной базой можно было работать. Так же можно сделать?

2024-08-08 12:16 UTC, foxprogs commented on supabase/migrations/202408011446_int.sql
> +    "id" "uuid" NOT NULL,
тут надо может указать что этот айди связан с таблицей auth.users? Или тогда не получается удалять?

2024-08-08 12:20 UTC, foxprogs commented on app/[lng]/private/components/UserGreeting.js
> +      console.error('Ошибка при выходе из системы')
русский язык, если код не будет правиться то лучше сразу хорошо сделать

2024-08-08 12:23 UTC, foxprogs commented on app/[lng]/private/components/UserGreeting.js
> +'use client'
тут тоже можно серверным сделать, если нужен только редирект

2024-08-08 12:24 UTC, foxprogs commented on app/[lng]/login/page.js
> +'use client'
все же я за то чтобы page.jsx у нас всегда был серверным компонентом. То есть мы все по максимуму делаем на сервере, а все что не можем - переносим на клиента

2024-08-08 12:29 UTC, foxprogs reviewed
есть вопросы по коду. И еще такой момент, я не могу через vscode сделать коммит, ругается что 
```
.husky/pre-commit: 1: npm: not found
husky - pre-commit script failed (code 127)
husky - command not found in PATH=...
```

2024-08-08 12:44 UTC, Valyukhov commented on .github/workflows/production.yml
> +      - master
такой ветки нет

2024-08-08 12:51 UTC, Valyukhov commented on app/[lng]/error/page.jsx
> +          onClick={() => router.push('/login')}
на будущее все роуты, которые ведут на другую страницу лучше делать не кнопками, а с помощью LINK, для семантики.
А всё, что остаётся на странице, либо какая-то сложная логика - тогда уже кнопками.

2024-08-08 13:47 UTC, Valyukhov commented on app/[lng]/login/page.js
> +      setError(err.message || 'Произошла ошибка.')
все логи / ошибки на английском пишем

2024-08-08 13:57 UTC, Valyukhov commented on app/[lng]/private/actions/PrivateRoute.js
большой буквы только компоненты называть, все остальные файлы - с маленькой

2024-08-08 14:00 UTC, Valyukhov commented on app/[lng]/private/actions/PrivateRoute.js
и не совсем понятно название - экшен про взять юзера, а название - общее - PrivateRoute

2024-08-08 14:25 UTC, DenisArger commented
> .husky/pre-commit: 1: npm: not found
> husky - pre-commit script failed (code 127)
> husky - command not found in PATH=...
@DenisArger возможно не хватает прав. Попробуй: chmod +x .husky/pre-commit

2024-08-08 15:42 UTC, foxprogs commented
> > .husky/pre-commit: 1: npm: not found
> > husky - pre-commit script failed (code 127)
> > husky - command not found in PATH=...
> > @foxprogs возможно не хватает прав. Попробуй: chmod +x .husky/pre-commit

Не помогло. В игструкциях написано про то что нужен какой-то доп код, который я в прошлый раз сказал удалить)

2024-08-12 04:49 UTC, foxprogs requested changes
есть замечания по коду

2024-08-12 10:12 UTC, DenisArger commented on app/[lng]/private/actions/getUser.js
> +  }
@foxprogs это касается все запросов? У меня сейчас GET запрос, который внутри себя закрывает сессию с SB и делает редирект на страницу авторизации.

2024-08-12 11:34 UTC, DenisArger commented on app/api/hello/route.js
Он сейчас используется в swagger

2024-08-12 12:14 UTC, DenisArger commented on app/[lng]/private/actions/getUser.js
> +  }
Я перенес редирект на страницу

2024-08-12 12:24 UTC, foxprogs commented on app/[lng]/private/actions/getUser.js
> +  }
> @foxprogs это касается всех запросов? У меня сейчас GET запрос, который внутри себя закрывает сессию с SB и делает редирект на страницу авторизации.

По поводу разлогина, по идее это норм, там и должна быть такая логика. Хотя понятно, что будут исключения. Я в общем думаю, если есть функция, пусть она всегда возвращает результат или выкидывает эксцепшн.

2024-08-12 16:28 UTC, Valyukhov commented on app/[lng]/login/actions.js
> +      window.location.href = '/password-reset-sent'
а почему не используешь
import { redirect } from 'next/navigation'
redirect('/password-reset-sent')
тогда это будет сервер

2024-08-12 16:36 UTC, Valyukhov commented on app/[lng]/login/components/AuthButtons.js
> +const AuthButton = ({ name, type, label, className }) => (
название  файла - множественное - AuthButtons, а у компонента - обычное- AuthButton, это может путать.
множественным числом именнуем только коллекции, массивы, обьекты

2024-08-12 18:42 UTC, foxprogs approved these changes

2024-08-12 18:45 UTC, Valyukhov commented on app/[lng]/login/components/InputField.js
> +  { id, name, type, required, label, value, onChange },
если много внутренних пропсов по-умолчанию - можно передать в одном параметре
`{id,label, ...props}`
а в jsx распатовать
```
 <input
        id={id}
        ref={ref}
        {...props} 
      />

```

2024-08-12 18:58 UTC, Valyukhov commented on app/supabase/middleware.js
> +    process.env.NEXT_PUBLIC_SUPABASE_URL,
а где хранить эти переменные?
NEXT_PUBLIC_SUPABASE_URL
в каком файле?

2024-08-12 19:02 UTC, Valyukhov reviewed
Есть комментарии

2024-08-13 07:25 UTC, DenisArger commented on app/supabase/middleware.js
> +    process.env.NEXT_PUBLIC_SUPABASE_URL,
добавил .env.example

2024-08-13 09:39 UTC, Valyukhov approved these changes

2024-08-13 09:42 UTC, merged