Add database schema
glokascom/bibleVis pull request #61
Opened 2024-08-16 18:04 UTC by Valyukhov

2024-08-16 19:27 UTC, foxprogs requested changes
есть замечания

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "is_deleted" BOOLEAN DEFAULT false,
лучше не булево а ставить дату deleted_at

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "prompt" VARCHAR(200),
кажется что это коротковатое поле для промпта)

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "is_ai_generated" BOOLEAN DEFAULT false,
мы в первую очередь ориентированны на AI по этому я бы тут TRUE ставил

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "description" VARCHAR(200),
не знаю, мне кажется коротковатым поле

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "id" SERIAL PRIMARY KEY,
мне кажется что такое поле не супер. Это ж уникальный айди будет у картинок 1,2,3,4,5.... А как тогда будет ссылка в браузере? Я бы два варианта рассмотрел, или uuid(но он слишком длинный. Можно конечно конвертировать его в base64, тогда вместо 36 символов получим 22, но и это достаточно длинный), или же завести еще одно поле для уникального айди картинки

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "description" VARCHAR(200),
я бы лучше явно к каждому полю прописывал, NOT NULL если оно не может быть таковым. Или же null в качестве дефолтного ставил.

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "file_size" INT,
еще нужна ориентация картинки

2024-08-16 19:27 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
не хватает таблицы просмотров картинки, поля в таблице картинок с количеством просмотров или какой-то отдельной сводной по этим данным, хотя бы по дням или по неделям, чтобы нам постоянно самим не считать это.
Так же таблицы скачиваний.
Не включен у тебя рлс на таблицах, а это потенциальная уязвимость же, так что надо включить

2024-08-18 16:58 UTC, Valyukhov commented on supabase/migrations/20240816163601_schema_db.sql
> +);
ну я пока вижу роль админа, модератора, создателя

2024-08-18 19:02 UTC, foxprogs reviewed
есть комментарии

2024-08-18 19:02 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "viewer_id" UUID, -- can be NULL if viewed by an unauthorized user
надо прописать что может быть NULL и default NULL

2024-08-18 19:02 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "downloader_id" UUID, -- can be NULL if downloaded by an unauthorized user
то же самое тут

2024-08-19 07:38 UTC, DenisArger commented on supabase/migrations/20240816163601_schema_db.sql
> +);
> как будет работать эта таблица? Будут ли у нас со временем новые роли? Или может вместо таблицы просто список завести?
@foxprogs что ты подразумеваешь под списком? Где он будет храниться?

2024-08-19 08:01 UTC, DenisArger reviewed
Оставил несколько замечаний и предложений.

2024-08-19 08:01 UTC, DenisArger commented on supabase/migrations/20240816163601_schema_db.sql
> +    "image_id" INT NOT NULL,
Если хотим получить все лайки  для изображения, тоже нужен индекс.

2024-08-19 11:17 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    ADD COLUMN IF NOT EXISTS "username" VARCHAR(50) UNIQUE,
может добавим количество фоловеров, чтобы не тянуть с другой таблицы

2024-08-19 11:18 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +ALTER TABLE "public"."users"
и еще вопрос, там поле blocked это дата или булево? Давай сразу сделаем дату, чтобы потом не менять

2024-08-19 11:20 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "url_slug" VARCHAR(50) UNIQUE NOT NULL DEFAULT gen_random_slug(),
хотелось бы 10-12 максимум, 50 это много. Сейчас это не принципиально, если будет огромная база то тогда это экономия места

2024-08-19 11:21 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    "url_slug" VARCHAR(50) UNIQUE NOT NULL DEFAULT gen_random_slug(),
и второй вопрос - что будет, если он сгенерит не уникальный айди?
не даст создать картинку или как? Может в функцию генерации добавить select по айди, и все завернуть в цикл while

2024-08-19 11:23 UTC, foxprogs commented on supabase/migrations/20240816163601_schema_db.sql
> +    slug := substring(translate(encode(gen_random_bytes(6), 'base64'), '/+', 'ab'), 1, 10);
а тут учтено что не должно быть / чтобы юрл нормально работал?

2024-08-19 11:51 UTC, Valyukhov commented on supabase/migrations/20240816163601_schema_db.sql
> +    slug := substring(translate(encode(gen_random_bytes(6), 'base64'), '/+', 'ab'), 1, 10);
@Valyukhov 
Base64-кодирование может включать символы / и +, которые не подходят для использования в URL без кодирования.
Чтобы избежать использования этих символов, в коде используется translate, который заменяет символы / и + на символы a и b соответственно.
После этого сгенерированная строка обрезается до 10 символов с помощью substring.
Таким образом, функция генерирует slug, который состоит только из букв и цифр, без проблемных символов для URL.

2024-08-19 12:09 UTC, foxprogs approved these changes

2024-08-19 12:10 UTC, merged